# Generated by Django 4.0.2 on 2022-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
